In [1]:
import torch

print(torch.__version__)

2.10.0+cpu


# Torch ops

### torch.add() :

In [13]:
a = torch.ones((2,2))
b= torch.add(a,5)
torch.add(a,1,alpha=5.0,out=a)
print(b)
print(b.dtype)
print(a)
print(a.dtype)

tensor([[6., 6.],
        [6., 6.]])
torch.float32
tensor([[6., 6.],
        [6., 6.]])
torch.float32


### torch.arange() :

In [28]:
print(torch.arange(5))
print(torch.arange(5).dtype)
print(torch.arange(0,1,0.1))
print(torch.arange(0,1,0.1).dtype)
print(torch.arange(1,0,-0.1,dtype=torch.float64))
print(torch.arange(1,0,-0.1,dtype=torch.float64).dtype)


tensor([0, 1, 2, 3, 4])
torch.int64
tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
torch.float32
tensor([1.0000, 0.9000, 0.8000, 0.7000, 0.6000, 0.5000, 0.4000, 0.3000, 0.2000,
        0.1000], dtype=torch.float64)
torch.float64


In [41]:
x= torch.arange(10.0,requires_grad=True)
y = (x**2).sum()
print(y)
y.backward()
print("derivative of x:", x.grad)

tensor(285., grad_fn=<SumBackward0>)
derivative of x: tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.])


### torch.reshape()

In [ ]:
a=torch.arange(10)
print(torch.reshape(a,(2,5)))
print(torch.reshape(a,(-1,2)))
a.reshape(-1,)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### torch.gather()

In [59]:
a=torch.arange(1,10).reshape(3,3)
idx=torch.tensor([[0,1],[0,1]])
print(a)
torch.gather(a,dim=1,index=idx)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


tensor([[1, 2],
        [4, 5]])

### torch.transpose()

In [73]:
a=torch.arange(9).reshape(3,3)
print(a)
print(torch.transpose(a,0,1))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


### torch.select()

In [92]:
a=torch.arange(6).reshape(2,3)
print(a)
print(a.select(1,0))
print(a.select(1,1))
print(a.select(1,2))


tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([0, 3])
tensor([1, 4])
tensor([2, 5])


### torch.select() :

In [142]:
a= torch.arange(9).reshape(3,3).float()
print(a)
idx=torch.tensor([[2,0,2],[1,1,0],[0,2,1]])
torch.zeros(4,4).scatter_(0,idx,a)

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])


tensor([[6., 1., 5., 0.],
        [3., 4., 8., 0.],
        [0., 7., 2., 0.],
        [0., 0., 0., 0.]])

### torch.normal() :

In [178]:
print(torch.normal(mean=0,std=0,size=(1,50)))
print(torch.mean(torch.normal(mean=0,std=0,size=(1,50))))
print(torch.normal(mean=0,std=1,size=(1,50)))
print(torch.mean(torch.normal(mean=0,std=1,size=(1,50))))

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0.]])
tensor(0.)
tensor([[ 0.8810,  0.7040, -0.5490,  0.2503, -0.8033, -0.8566,  0.2133, -0.7203,
         -1.8602, -0.3901,  2.0039, -0.5698,  1.5816,  0.6515, -0.0655,  0.0815,
         -0.8036,  1.2516,  0.2715,  0.9150, -0.8137, -2.0093, -0.8975, -0.1822,
         -0.6759,  1.4722,  0.6150, -0.2631,  0.0105, -0.3632, -0.9684,  1.7823,
          1.2440,  0.6631, -2.1994,  0.2371,  0.7951,  0.2962, -0.1952,  0.4199,
         -1.7939, -0.4814,  1.1594, -1.9787, -0.1552, -0.4497,  0.6789, -0.2581,
         -1.9999,  1.1574]])
tensor(0.1150)
